### ISSUE TITLE
Italics and bold do not work with variable-width font

### ISSUE THREAD

**Issue by reagle** [sekogan/MarkdownLight#14]
I edit markdown as "font_face": "Georgia" and italics and bold do not work. They do with "Liberation Mono".

**Comment by ivan** [comment]
That's a Sublime Text limitation.

https://github.com/SublimeTextIssues/Core/issues/279

**Comment by reagle** [comment]
Yes, and I just saw [this discussion](https://github.com/blog/2289-publishing-with-github-pages-now-as-easy-as-1-2-3). Sounds like it will not be fixed; closing here.
