### ISSUE TITLE
dark theme?

### ISSUE THREAD

**Issue by tals** [sekogan/MarkdownLight#3]
While the name is MarkdownLight, it would be really nice to have a theme for dark-mode users :)
The other markdown packages for Sublime are not as good as yours (notably, MarkdownEditing produces rather ugly results).

**Comment by nvtkaszpir** [comment]
https://github.com/nvtkaszpir/MarkdownLight fast edit, haven't got time to properly rename it and so on.

**Comment by tals** [comment]
Neat!

**Comment by michael-jahn-dev** [comment]
+1

**Comment by sekogan** [comment]
Thanks for PR, merged to 0.6.0.
