### ISSUE TITLE
How to use the dark version?

### ISSUE THREAD

**Issue by michael-jahn-dev** [sekogan/MarkdownLight#5]
Hey,

I cannot get the dark markdown theme to work, could you explain how to use it and update the repo readme? :)

Greets!

**Comment by sekogan** [comment]
Hi!

Thanks for asking. Added [a small recipe](https://github.com/sekogan/MarkdownLight#how-to-use-the-dark-color-scheme) to the readme.
Does it solve the issue?

**Comment by michael-jahn-dev** [comment]
Hey,

really nice thank you. That worked  :)
