### ISSUE TITLE
All contents are rendered as italics after a italic syntax ended with a URL without a space.

### ISSUE THREAD

**Issue by jfcherng** [sekogan/MarkdownLight#7]
Markdown source:

```
_You may also visit https://github.com_
Other contents...
```

Current result:
![2015-10-05_09-56-29](https://cloud.githubusercontent.com/assets/6594915/10271773/638d5d94-6b48-11e5-9fce-ed4dad609324.png)

Expected result:
![2015-10-05_10-01-02](https://cloud.githubusercontent.com/assets/6594915/10271772/638bfb34-6b48-11e5-9092-afce17e664b9.png)

I know, for a user, a space can be placed after the URL to fix this though.

**Comment by sekogan** [comment]
Thanks for reporting!

**Comment by jfcherng** [comment]
Thanks ;)
