### ISSUE TITLE
[Dark theme] Braces highlighted in black colour

### ISSUE THREAD

**Issue by aviaryan** [sekogan/MarkdownLight#8]
I noticed that sometimes braces get highlighted in black colour and thus become invisible when using the Dark theme. I have to select them to reveal them.
Infact when braces are highlighted black everything inside them becomes black too. (this happens in java)

![part1](https://cloud.githubusercontent.com/assets/4047597/10994988/bd99c97e-849f-11e5-980a-54c7ceb19151.png)
![part2](https://cloud.githubusercontent.com/assets/4047597/10994993/c3acc2f8-849f-11e5-87d0-7439429f0a2b.png)

Another thing I notice is that this generally happens inside a `class` declaration, be it in java or c++.

For example, try this c++ code http://pastebin.com/gibqVZep
The part inside the class is not highlighted at all.

![cpp](https://cloud.githubusercontent.com/assets/4047597/10995199/20f32a96-84a1-11e5-9da3-34c553f8cdcd.png)

**Comment by sekogan** [comment]
Thanks for reporting. The issue with Java braces looks like a bug in the dark theme, easy to fix.

The second issue is a duplicate of #2.
